version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    environment:
      - PORT
      - API_KEY
      - FETCH_INTERVAL
    ports:
      - 0.0.0.0:$PORT:$PORT
