version: "3.9"
services:
  backend:
    container_name: tjanx-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=$BACKEND_PORT
      - API_KEY
      - FETCH_INTERVAL
    expose:
      - $BACKEND_PORT
    networks:
     - main-network
  frontend:
    container_name: tjanx-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BASE_PATH=$BASE_PATH
        - VITE_WEBSOCKET_PORT=$PORT
        - VITE_SECURE=$SECURE
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - 80
    networks:
     - main-network

networks:
  main-network:
    name: main-network
    external: true