FROM rust:1.69 as build

RUN USER=root cargo new --bin backend
WORKDIR /backend

COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

RUN cargo build
RUN rm src/*.rs

COPY ./src ./src

RUN rm ./target/debug/deps/backend*
RUN cargo build



FROM rust:1.69-slim-buster

COPY --from=build /backend/target/debug/backend .

CMD ["./backend"]